// <auto-generated />
using System;
using InsuranceWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceWebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("InsuranceWebAPI.Models.InsurancePolicy", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("InsuranceAmount")
                        .HasColumnType("REAL");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("InsurancePolicies");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            EndDate = new DateTime(2025, 6, 23, 11, 31, 4, 88, DateTimeKind.Local).AddTicks(1805),
                            InsuranceAmount = 50000.0,
                            PolicyNumber = "POL123456",
                            StartDate = new DateTime(2024, 6, 23, 11, 31, 4, 88, DateTimeKind.Local).AddTicks(1747),
                            UserID = 1
                        },
                        new
                        {
                            ID = 2,
                            EndDate = new DateTime(2025, 6, 23, 11, 31, 4, 88, DateTimeKind.Local).AddTicks(1812),
                            InsuranceAmount = 75000.0,
                            PolicyNumber = "POL654321",
                            StartDate = new DateTime(2024, 6, 23, 11, 31, 4, 88, DateTimeKind.Local).AddTicks(1811),
                            UserID = 2
                        });
                });

            modelBuilder.Entity("InsuranceWebAPI.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "john.doe@example.com",
                            Name = "John Doe"
                        },
                        new
                        {
                            ID = 2,
                            Email = "jane.smith@example.com",
                            Name = "Jane Smith"
                        });
                });

            modelBuilder.Entity("InsuranceWebAPI.Models.InsurancePolicy", b =>
                {
                    b.HasOne("InsuranceWebAPI.Models.User", "User")
                        .WithMany("InsurancePolicies")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceWebAPI.Models.User", b =>
                {
                    b.Navigation("InsurancePolicies");
                });
#pragma warning restore 612, 618
        }
    }
}
